rama_2
emmueito/TP-1 pull request #2
Opened 2024-07-13 12:38 UTC by emmueito

Buenos días colegas. 9:35 hs del día 13/07/2024 Creo una nueva rama para su revision. Buen sábado

2024-07-13 14:01 UTC, alutenberg commented
Ok! Lo agregué a la lista de revisión. Sugiero que arranques con el TP2 aunque no esté corregido todavía este TP1.

2024-07-13 15:27 UTC, emmueito commented
Genial, ¡muchas gracias!

El sáb, 13 jul 2024, 11:01, alutenberg ***@***.***> escribió:

> Ok! Lo agregué a la lista de revisión. Sugiero que arranques con el TP2
> aunque no esté corregido todavía este TP1.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/emmueito/TP-1/pull/2#issuecomment-2226917032>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BA4SC2ICFDXGT7CIFC45ONTZMEXLHAVCNFSM6AAAAABK2HYWYKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDEMRWHEYTOMBTGI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-07-13 23:39 UTC, scaprile requested changes

2024-07-13 23:39 UTC, scaprile commented on README.md
> +
No sé qué hace esto acá, pero no lo miro

2024-07-13 23:39 UTC, scaprile commented on main.cpp
> +#define OFF  !(ON) //Declaracion de MACRO
El paréntesis se usa para que cuando se usa la macro no se pelee con el resto del código.
Es innecesario en este caso, y si lo querés poner por la razón anterior, el `!` va adentro de los paréntesis.

2024-07-13 23:39 UTC, scaprile commented on main.cpp
> +#define delay(ms)   thread_sleep_for(ms)
No intentes adecuar un Lamborghini a un Fiat 600.
Yo veo delay() y digo "qué es eso !?", y tengo que venirme hasta acá arriba a ver qué hiciste. Por qué torturás a los revisores ?

2024-07-13 23:39 UTC, scaprile commented on main.cpp
> +#define TIEMPO_ENTRE_MUESTRAS   10
10 qué ? Segundos, vueltas, milisegundos, horas, ciclos geológicos ?

2024-07-13 23:39 UTC, scaprile commented on main.cpp
> +int registroTiepoAcumulado = 0;
elm tiepo quém cosam esm ?

2024-07-13 23:39 UTC, scaprile commented on main.cpp
> +    initOuputs();
Al menos sos consistente. Sería ou**t**puts

2024-07-13 23:39 UTC, scaprile commented on main.cpp
> +    float tempC = temp * 3.3/0.01;
y estos números mágicos de dónde salen ?

2024-07-13 23:39 UTC, scaprile commented on main.cpp
> +    if(lm35TempC >= maxTempPermitida){
El `=` no tiene sentido con números en coma flotante

2024-07-13 23:39 UTC, scaprile commented on main.cpp
> +        }
Y acá se queda bloqueado en esta función sin hacer ninguna otra cosa ni responder a nada, hasta que se enfríe, si alguna vez sucede.
No, no, no.

2024-07-13 23:39 UTC, scaprile commented on main.cpp
> +    if(lm35TempC <= minTempPermitida){
`=`

2024-07-13 23:39 UTC, scaprile commented on main.cpp
> +        }
Mismo comentario que para el ventilador.

Además, tenés una dependencia innecesaria entre 2 funciones con una tercera.

2024-07-13 23:39 UTC, scaprile commented on main.cpp
> +    int stringLength = strlen(str);   //Keil Studio no me tomó la función strlen()
```
$man sprintf

RETURN VALUE
       Upon successful return, these functions return the number of characters
       printed (excluding the null byte used to end output to strings).
```

2024-07-13 23:39 UTC, scaprile commented on main.cpp
> +    registroTiempoAcumulado = registroTiempoAcumulado + TIEMPO_ENTRE_MUESTRAS;
Excepto que todo el tiempo que se quedó bloqueado enfriando o calentando, no lo viste pasar...

2024-07-14 19:39 UTC, emmueito commented on README.md
> +
Hola Sergio. Gracias!!

2024-07-14 19:39 UTC, emmueito commented on main.cpp
> +#define OFF  !(ON) //Declaracion de MACRO
Entiendo. Muchas Gracias!!

2024-07-14 19:39 UTC, emmueito commented on main.cpp
> +#define delay(ms)   thread_sleep_for(ms)
Juro que me da mucha vergüenza. Pero me la aguanto y sigo. Si bien entregue este Código para cumplir con los tiempo. no lo entiendo aun. tenme paciencia por favor. algún día pagare tu inversion (tiempo perdido) en mi!!! voy despacito pero llego al tp final. confia en mi!!!

2024-07-14 19:39 UTC, emmueito commented on main.cpp
> +#define TIEMPO_ENTRE_MUESTRAS   10
en unos días lo resuelvo.

2024-07-14 19:41 UTC, emmueito commented on main.cpp
> +int registroTiepoAcumulado = 0;
tiempo!!1 jajaaj perdon perdon perdon

2024-07-14 19:41 UTC, emmueito commented on main.cpp
> +        }
ok. lo resuelvo

2024-07-14 19:42 UTC, emmueito commented on main.cpp
> +    if(lm35TempC <= minTempPermitida){
entiendo.

2024-07-14 19:44 UTC, emmueito commented on main.cpp
> +        }
estoy traduciendo el libro!! por que ando flojo en ingles. por eso me atrasare. pero acelero al final. y subo al podio!!!

2024-07-14 19:45 UTC, emmueito commented on main.cpp
> +    int stringLength = strlen(str);   //Keil Studio no me tomó la función strlen()
VALOR DEVUELTO
       Al devolverse correctamente, estas funciones devuelven el número de caracteres
       impreso (excluyendo el byte nulo utilizado para finalizar la salida en cadenas). Esta bien la traducción!?

2024-07-14 19:47 UTC, emmueito commented on main.cpp
> +    registroTiempoAcumulado = registroTiempoAcumulado + TIEMPO_ENTRE_MUESTRAS;
No entiendo bien esta parte aun. pero ya llego jajajja perdon no se que decir

2024-07-14 20:02 UTC, scaprile commented on main.cpp
> +        }
Mal, tenés que entender Inglés de una, o leer libros en castellano.

2024-07-14 20:04 UTC, scaprile commented on main.cpp
> +    int stringLength = strlen(str);   //Keil Studio no me tomó la función strlen()
Más o menos, imagino que uno no habla así, pero lo importante es que entiendas que llamar a strlen() después de esto es algo como redundante o innecesario si uno sabe lo que está haciendo

2024-07-14 20:06 UTC, scaprile commented on main.cpp
> +    registroTiempoAcumulado = registroTiempoAcumulado + TIEMPO_ENTRE_MUESTRAS;
Que estás contabilizando "tiempo" y arriba te quedaste esperando y el tiempo transcurrió...
Deberías entender lo que hace tu programa, con los debuggers en circuito que hay hoy, no tenés excusa, si no entendés por qué pasa algo, lo simulás o lo ejecutás paso a paso y vas viendo qué hace cada cosa.

2024-07-14 20:17 UTC, emmueito commented on main.cpp
> +    registroTiempoAcumulado = registroTiempoAcumulado + TIEMPO_ENTRE_MUESTRAS;
Si. Entiendo. voy a hacer eso. paso a paso. 4 dias y entrego algo mas coherente. buen domingo

2024-07-16 09:32 UTC, emmueito commented on main.cpp
> +    float tempC = temp * 3.3/0.01;
Hola Sergio. Aqui encontré la respuesta!!! Esta fórmula indica que la lectura analógica, que es un valor no entero entre 0 y 1, se multiplica primero por 3.3 V para obtener el voltaje correspondiente. Esto se debe al hecho de que el conversor analógico a digital de la placa NUCLEO proporciona aproximadamente 0.0 para una entrada de 0 V y da su valor máximo (en este caso 1.0) para una entrada de 3.3 V. 
A continuación, el resultado se divide por 0.01 V/°C porque la señal de salida VOUT del LM35 aumenta en 10 mV/°C en el rango de 2 a 150°C. 
 La fórmula de conversión de Celsius a Fahrenheit es:
Temperatura [°F] = Temperatura [°C] × 9/5 + 32 (2)

2024-07-16 09:38 UTC, emmueito commented on main.cpp
> +    int stringLength = strlen(str);   //Keil Studio no me tomó la función strlen()
Si, lo entiendo ahora. Me devuelve el numero de caracteres que ocupa el string . de esta forma no tengo que contar cuanto espacio necesitaría para ingresar la frase completa que imprimiré en el monitor serie.

2024-07-16 09:43 UTC, emmueito commented on main.cpp
> +        }
ok. Es lógico, pero en mi caso estor invertido. ( !ingles)

2024-07-16 22:48 UTC, scaprile commented on main.cpp
> +    float tempC = temp * 3.3/0.01;
Esto deberías haberlo sabido antes de escribirlo ahí, y puesto breve y conciso en un comentario:
```// [0;1] -> 3.3V, 10mV/°C```
o algo por el estilo

Lo otro hablalo con Lord Fahrenheit, hace siglos que no cambia

2024-07-16 23:53 UTC, emmueito commented on main.cpp
> +    float tempC = temp * 3.3/0.01;
Loi intuía. Y lo otro es facil!!  Grados Celsius . 0° -100° Faren...... 32° - 212.     
100- 0 = 100°
212- 32 = 180°
de ahi ( 9/5 o 5/9) relación de conversion 
de f a c = ( f-32 ) * 5/9
de c a f = c * (9/5) + 32
Sigo aprendiendo!! Gracias por tomarte el tiempo.

2024-07-24 03:10 UTC, closed without merging